name: Deploy Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          APP_PATH: '/var/store'
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Ensure PATH includes the location of PM2 and Node.js
            export PATH=$PATH:/root/.nvm/versions/node/v20.16.0/bin

            cd $APP_PATH

            # Pull the latest code from the repository
            git pull 

            # Install dependencies
            yarn 
          
           # Build 
            yarn build 

            # Reload PM2 process
            pm2 reload 1

            # Save pm2 
            pm2 save
            
          EOF
