name: Deploy Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          APP_PATH: '/var/store'
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Ensure PATH includes the location of PM2 and Node.js
            export PATH=$PATH:/root/.nvm/versions/node/v20.16.0/bin
            
            # Navigate to the application directory
            cd $APP_PATH

            # Pull the latest code from the repository
            echo "Pulling latest code from repository..."
            git pull origin main

            # Install dependencies
            echo "Installing dependencies..."
            yarn 

            # Build the project
            echo "Building the project..."
            yarn build 

            # Reload PM2 process (use the process name if you’re unsure of the ID)
            echo "Reloading PM2 process..."
            pm2 reload app-name || { echo 'PM2 reload failed'; exit 1; }

            # Save PM2 process list
            echo "Saving PM2 process list..."
            pm2 save || { echo 'PM2 save failed'; exit 1; }
          EOF
