name: Deploy Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          APP_PATH: '/var/store'
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Load NVM and set PATH
            source /root/.nvm/nvm.sh
            export PATH=$PATH:/root/.nvm/versions/node/v20.16.0/bin

            # Navigate to the application directory
            cd "/var/store" || { echo 'Directory not found'; exit 1; }

            # Output current directory and files for debugging
            echo "Current directory: $(pwd)"
            echo "Directory contents:"
            ls -la

            # Ensure this is a Git repository
            if [ ! -d ".git" ]; then
              echo "Not a Git repository. Exiting."
              exit 1
            fi

            # Pull the latest code from the repository
            echo "Pulling latest code from repository..."
            git pull || { echo 'Git pull failed'; exit 1; }

            # Install dependencies
            echo "Installing dependencies..."
            yarn || { echo 'Yarn install failed'; exit 1; }

            # Build the project
            echo "Building the project..."
            yarn build || { echo 'Yarn build failed'; exit 1; }

            # Reload PM2 process (use the process name or correct ID)
            echo "Reloading PM2 process..."
            pm2 reload 1 --update-env || { echo 'PM2 reload failed'; exit 1; }

            # Save PM2 process list
            echo "Saving PM2 process list..."
            pm2 save || { echo 'PM2 save failed'; exit 1; }
          EOF
